import NavMenu from "./NavMenu"
import AuthProvider from "./AuthProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          <div className="container">
            <NavMenu/>
            {children}
          </div>
          </body>
      </html>
    </AuthProvider>

  )
}
